### ISSUE TITLE
Thoughts on omitting `for` and `keyFor`?

### ISSUE THREAD

**Issue by ljharb** [WebReflection/get-own-property-symbols#3]
`Symbol.for` and `Symbol.keyFor` can't be shimmed cross-realm, which is one of its primary purposes.

What would you think about removing those methods entirely?

If not, then at least it should be a documented caveat in the README.

**Comment by WebReflection** [comment]
will put them in the README too. Agreed, cross-realm is a whole new world of messness for any sort of polyfill.

**Comment by WebReflection** [comment]
I've updated this and other [caveats](https://github.com/WebReflection/get-own-property-symbols#caveats) ... if that's OK for you please close this bug.

Thanks

**Comment by ljharb** [comment]
Looks good, thanks
