### ISSUE TITLE
Symbol.keyFor is not spec compliant

### ISSUE THREAD

**Issue by JakeChampion** [WebReflection/get-own-property-symbols#6]
>**19.4.2.5 Symbol.keyFor ( sym )**
>
>When Symbol.keyFor is called with argument sym it performs the following steps:
>  1. If Type(sym) is not Symbol, throw a TypeError exception.
>
>  2. For each element e of the GlobalSymbolRegistry List (see 19.4.2.1),
>
>     a. If SameValue(e.[[symbol]], sym) is true, return e.[[key]].
>  3. Assert: GlobalSymbolRegistry does not currently contain an entry for sym.
>
>  4. Return undefined.

I think this may be possible using a prototype check instead of a `typeof` check.

**Comment by ljharb** [comment]
A prototype check is never cross-realm compatible, however.

**Comment by WebReflection** [comment]
what @ljharb said but I'm actually not sure I understand the problem.

Are you saying it should throw? Where native supported that would happen anyway, not sure it's a real concern but it might be fixable.

If you are talking about global cross realm thing ... that might be achievable dropping the random bit of this polyfill, assuming any other polyfill use the exact same version and same code used in the other realm.

worth exploring, will leave it open for now (hoping for extra clarifications or suggestions)

**Comment by JakeChampion** [comment]
I'm commenting on the fact it should throw and currently does not in this polyfill.

I've added this to my implementation of `keyFor`:
```js
if (Object.prototype.toString.call(symbol) !== "[object Symbol]") {
	throw new TypeError(symbol + ' is not a symbol');
}
```

It can definitely be improved.

**Comment by WebReflection** [comment]
Not sure it's a want fix then, it would throw in 90% of the cases where supported natively, there's much more this poly cannot cover if we take specs as reference. Why do you think that's needed? Are you validating ES6 via test262 using a polyfill? Any particular security concern? I'd like to see the benefit beside full specs compliancy that I know already it's unfortunately not possible

**Comment by ljharb** [comment]
@JakeChampion that fails when Symbol.toStringTag is used. You'd need https://npmjs.com/is-symbol which is not compatible with Symbol shams like this one.

I'm a staunch advocate for spec compliance but if you want that, you wouldn't be attempting to polyfill Symbol, since typeof can't be shimmed - so I think in this case that check might not be valuable.

**Comment by JakeChampion** [comment]
I'm looking at creating a set of Symbol polyfills for the [polyfill-service](https://github.com/Financial-Times/polyfill-service/pull/585)

**Comment by ljharb** [comment]
@JakeChampion This very project is the one that complies the very most with the spec on Symbols - I am very skeptical that any project could deviate from what this one does and improve the compliance (including cross-realm compatibility) - if you have such improvements, please PR them in! I would highly recommend using this project for your polyfill service rather than reinventing the wheel.

**Comment by JakeChampion** [comment]
I have pulled the individual polyfills out into separate modules -- https://github.com/Financial-Times/polyfill-service/tree/symbol/polyfills/Symbol

**Comment by ljharb** [comment]
That is unwise, as the attempt to polyfill Symbol is utterly useless unless done wholesale.

**Comment by JakeChampion** [comment]
How so?
If a browser has Symbol but not specific well-known Symbols, this will create those well-known Symbols using their native Symbol constructor.
Have I misread some part of the specification?

**Comment by ljharb** [comment]
@JakeChampion ah ok, if you're just talking about well-known symbols, that's different :-) afaik this project does not attempt to polyfill any of the well-known symbols, just Symbols themselves.

**Comment by JakeChampion** [comment]
I think it does [here](https://github.com/WebReflection/get-own-property-symbols/blob/master/src/get-own-property-symbols.js#L229)

**Comment by ljharb** [comment]
welp, there you go then :-p sorry for the miscommunication

**Comment by JakeChampion** [comment]
I did modify the polyfill to [freeze the Symbol](https://github.com/Financial-Times/polyfill-service/blob/symbol/polyfills/Symbol/polyfill.js#L61) to [pass this test](https://github.com/Financial-Times/polyfill-service/blob/symbol/polyfills/Symbol/tests.js#L28).

**Comment by ljharb** [comment]
that seems like a good PR to add to this project :-D

**Comment by WebReflection** [comment]
I'm not sure I understand how that repository works ... it looks like you grabbed [this repo file](https://github.com/WebReflection/get-own-property-symbols/blob/master/src/get-own-property-symbols.js), dropped credits, changed tab size, removed some part, and [made it your file](https://github.com/Financial-Times/polyfill-service/blob/symbol/polyfills/Symbol/polyfill.js).

Can you please explain to me what is this about and what are you trying to achieve and why or for whom?

Thank you.

**Comment by JakeChampion** [comment]
Apologies for losing the credit information in the file, that has been added back with an extra comment leading to this repository and mentioning modifications have been made to the file.

The reasoning for modifying the file is because it is combining/applying multiple polyfills at once, which is something that the polyfill-service tries to avoid. The reason for that is to serve the minimum amount of polyfills required for a specific browser.

Some browsers already have a `Symbol` constructor, but don't have the other parts, such as `Object.getOwnPropertySymbols` and the collection of "well-known symbols". Instead of serving those browsers a pointless Symboll constructor polyfill, we will instead serve them only the polyfills they require.

**Comment by WebReflection** [comment]
this bug has been fixed and pushed with a test too.

for any other bug please open a ticket a part, thanks.

I will look into the frozen thing as soon as I have time
